In [13]:
import numpy as np
import pandas as pd

In [2]:
salary=[62031, 53195, 93867, 102937, 33372, 89989, 76958, 12469, 27979, 101515, 60212, 86937, 50417, 28548, 87680, 31738, 77495, 48232, 65052, 67633, 21637, 20039, 59136, 100622, 24586, 53475, 97165, 103241, 32023, 103394, 50072, 40819, 23819, 80856, 94567, 50863, 11926, 87687, 95453, 47499, 76026, 49628, 81393, 50240, 99609, 29034, 66682, 63807, 15972, 22455, 64450, 16992, 69607, 41786, 18901, 86832, 43261, 61381, 96317, 19555, 22194, 15684, 19774, 15293, 102666, 101037, 103538, 55388, 71802, 33490, 13226, 39113, 52670, 29431, 96883, 55355, 86107, 87194, 21476, 86930, 25909, 22029, 102136, 57148, 72578, 22813, 14657, 49341, 74068, 70752, 96763, 85531, 95399, 31688, 64463, 28954, 72344, 31559, 59578, 25407]

In [3]:
salary=sorted(salary)
print(salary)

[11926, 12469, 13226, 14657, 15293, 15684, 15972, 16992, 18901, 19555, 19774, 20039, 21476, 21637, 22029, 22194, 22455, 22813, 23819, 24586, 25407, 25909, 27979, 28548, 28954, 29034, 29431, 31559, 31688, 31738, 32023, 33372, 33490, 39113, 40819, 41786, 43261, 47499, 48232, 49341, 49628, 50072, 50240, 50417, 50863, 52670, 53195, 53475, 55355, 55388, 57148, 59136, 59578, 60212, 61381, 62031, 63807, 64450, 64463, 65052, 66682, 67633, 69607, 70752, 71802, 72344, 72578, 74068, 76026, 76958, 77495, 80856, 81393, 85531, 86107, 86832, 86930, 86937, 87194, 87680, 87687, 89989, 93867, 94567, 95399, 95453, 96317, 96763, 96883, 97165, 99609, 100622, 101037, 101515, 102136, 102666, 102937, 103241, 103394, 103538]

In [8]:
q1,q2,q3=np.percentile(salary,[25,50,75])

In [6]:
q1

29014.0

In [7]:
q3

86288.25

In [9]:
q2

56268.0

In [10]:
iqr=q3-q1

In [11]:
lower_fence=q1-(1.5*iqr)
higher_fence=q3+(1.5* iqr)

In [12]:
lower_fence

-56897.375

In [57]:
df=pd.read_csv('E:\Data Science\Datasets\housing.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [35]:
mv=df.isna().sum()
missing_rows = df[df.isna().any(axis=1)].shape[1]

In [36]:
missing_rows

81

In [23]:
df.shape[0]

1460

In [26]:
#total_rows = df.shape[0]
#missing_rows = df[df.isna().any(axis=1)].shape[0]
#percentage_missing = (missing_rows / total_rows) * 100

#print(f"Percentage of rows with missing values before dropping: {percentage_missing:.2f}%")

# Drop rows with missing values and calculate the percentage of rows dropped
df_dropped = df.dropna()
rows_dropped = total_rows - df_dropped.shape[0]
percentage_dropped = (rows_dropped / total_rows) * 100

print(f"Percentage of rows dropped: {percentage_dropped:.2f}%")

# Output the resulting DataFrame without missing values
print("DataFrame after dropping missing values:")
print(df_dropped)

Percentage of rows dropped: 100.00%
DataFrame after dropping missing values:
Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [28]:
df_dropped=df.dropna()
df_dropped

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [38]:
before=df.shape[0]
df=df.dropna()
after=df.shape[0]
ans=100*(before-after)/before
print(ans)

100.0

In [39]:
before

1460

In [41]:
a=df.dropna()
a

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [43]:
la=[]
la=df['LotArea'].tolist()
la

[8450,
 9600,
 11250,
 9550,
 14260,
 14115,
 10084,
 10382,
 6120,
 7420,
 11200,
 11924,
 12968,
 10652,
 10920,
 6120,
 11241,
 10791,
 13695,
 7560,
 14215,
 7449,
 9742,
 4224,
 8246,
 14230,
 7200,
 11478,
 16321,
 6324,
 8500,
 8544,
 11049,
 10552,
 7313,
 13418,
 10859,
 8532,
 7922,
 6040,
 8658,
 16905,
 9180,
 9200,
 7945,
 7658,
 12822,
 11096,
 4456,
 7742,
 13869,
 6240,
 8472,
 50271,
 7134,
 10175,
 2645,
 11645,
 13682,
 7200,
 13072,
 7200,
 6442,
 10300,
 9375,
 9591,
 19900,
 10665,
 4608,
 15593,
 13651,
 7599,
 10141,
 10200,
 5790,
 1596,
 8475,
 8635,
 10778,
 10440,
 13000,
 4500,
 10206,
 8892,
 8530,
 16059,
 11911,
 3951,
 8470,
 8070,
 7200,
 8500,
 13360,
 7200,
 9337,
 9765,
 10264,
 10921,
 10625,
 9320,
 10603,
 9206,
 7018,
 10402,
 7758,
 9375,
 10800,
 6000,
 8500,
 11751,
 9525,
 7750,
 9965,
 21000,
 7259,
 3230,
 11616,
 8536,
 12376,
 8461,
 21453,
 6060,
 9464,
 7892,
 17043,
 6780,
 4928,
 4388,
 7590,
 8973,
 14200,
 12224,
 7388,
 6853,
 10335,
 10400,
 10355,
 11070,
 9066,
 15426,
 10500,
 11645,
 8520,
 10335,
 9100,
 2522,
 6120,
 9505,
 7500,
 6240,
 10356,
 13891,
 14803,
 13500,
 11340,
 9600,
 7200,
 12003,
 12552,
 19378,
 11120,
 13688,
 12182,
 5500,
 5400,
 10106,
 10708,
 10562,
 8244,
 16669,
 12358,
 31770,
 5306,
 10197,
 12416,
 12615,
 10029,
 13650,
 17423,
 8520,
 2117,
 7588,
 9060,
 11426,
 7438,
 22950,
 9947,
 10410,
 7018,
 4923,
 10570,
 7472,
 9017,
 2522,
 7180,
 2280,
 9416,
 25419,
 5520,
 9591,
 8546,
 10125,
 7000,
 4438,
 3500,
 11851,
 13673,
 12493,
 14364,
 8250,
 5604,
 10420,
 8640,
 13568,
 10900,
 10011,
 8450,
 9906,
 15660,
 3010,
 8990,
 8068,
 11475,
 10500,
 13472,
 1680,
 9950,
 1869,
 8521,
 3182,
 8760,
 15138,
 1680,
 10650,
 7851,
 1680,
 8773,
 9453,
 12030,
 8741,
 9000,
 3880,
 5000,
 10762,
 8880,
 10400,
 9142,
 11310,
 11317,
 159000,
 5350,
 4750,
 8366,
 9350,
 8400,
 8738,
 8791,
 8814,
 12435,
 12702,
 19296,
 9588,
 8471,
 5500,
 5232,
 12090,
 11207,
 8400,
 6900,
 7917,
 10728,
 39104,
 11764,
 9600,
 8314,
 7264,
 9196,
 19138,
 14450,
 10005,
 11287,
 7200,
 5063,
 9612,
 8012,
 4251,
 9786,
 8125,
 9819,
 8730,
 15611,
 5687,
 11409,
 16659,
 9600,
 7937,
 13710,
 7399,
 11700,
 14000,
 15750,
 16226,
 13704,
 9800,
 18386,
 10386,
 13474,
 7920,
 12342,
 12378,
 7685,
 8000,
 7800,
 215245,
 9600,
 7795,
 13005,
 9000,
 9900,
 14115,
 16259,
 12099,
 10380,
 5820,
 11275,
 5000,
 10846,
 11600,
 11888,
 6402,
 10624,
 8176,
 10655,
 8198,
 9042,
 164660,
 14157,
 9135,
 14145,
 12400,
 14191,
 8400,
 8544,
 8849,
 2592,
 6435,
 12772,
 17600,
 2448,
 20431,
 7820,
 5271,
 9084,
 8520,
 8400,
 11249,
 9248,
 4224,
 6930,
 12011,
 7540,
 9144,
 7301,
 1680,
 18800,
 10690,
 9500,
 9150,
 7800,
 9830,
 8121,
 17120,
 7175,
 10634,
 8200,
 10020,
 8846,
 11143,
 11394,
 8123,
 5000,
 7200,
 9245,
 9000,
 53107,
 3182,
 8410,
 7200,
 9382,
 12474,
 8405,
 12209,
 8339,
 7446,
 10134,
 9571,
 7200,
 7590,
 8967,
 8125,
 14963,
 8767,
 10200,
 12090,
 10364,
 9991,
 10480,
 15576,
 14154,
 10800,
 9571,
 34650,
 4403,
 8960,
 11228,
 8899,
 7844,
 22420,
 8160,
 8450,
 7060,
 16635,
 21750,
 9200,
 9000,
 3378,
 12800,
 8593,
 6762,
 11457,
 1680,
 5586,
 1920,
 10839,
 1890,
 10667,
 4400,
 6000,
 4280,
 12354,
 15431,
 12108,
 6240,
 3922,
 8750,
 9855,
 16492,
 11214,
 8600,
 6000,
 5684,
 70761,
 9303,
 9000,
 9297,
 9600,
 4571,
 53227,
 5100,
 7015,
 8004,
 7200,
 8281,
 11988,
 8430,
 3072,
 10628,
 9480,
 11428,
 9291,
 6820,
 11952,
 3675,
 14977,
 5330,
 8480,
 13125,
 13693,
 10637,
 5925,
 16033,
 11846,
 2500,
 4500,
 7758,
 9600,
 10289,
 12243,
 10800,
 1526,
 2665,
 9490,
 15578,
 7931,
 5784,
 7879,
 12692,
 9120,
 7800,
 7535,
 1890,
 9803,
 9170,
 15602,
 2308,
 7596,
 9554,
 7862,
 9600,
 9600,
 14559,
 6792,
 9100,
 9187,
 10594,
 12220,
 10448,
 10208,
 9531,
 10918,
 10800,
 11988,
 5000,
 40094,
 11787,
 7500,
 13300,
 14948,
 9098,
 32668,
 10200,
 6155,
 7200,
 5000,
 9056,
 7000,
 8924,
 12735,
 11553,
 11423,
 14601,
 11000,
 10140,
 4058,
 17104,
 13837,
 8737,
 7244,
 8235,
 9375,
 4043,
 6000,
 11146,
 8777,
 10625,
 6380,
 14850,
 11040,
 21872,
 3196,
 11341,
 10010,
 13907,
 21780,
 13346,
 6858,
 11198,
 10171,
 12327,
 7032,
 13101,
 7332,
 13159,
 9967,
 10500,
 8480,
 6292,
 11777,
 3604,
 12150,
 14585,
 12704,
 11841,
 13500,
 6120,
 11443,
 10267,
 8740,
 25095,
 9100,
 8320,
 13478,
 6600,
 4435,
 7990,
 11302,
 3600,
 3922,
 12984,
 1950,
 10927,
 9000,
 10041,
 3182,
 12803,
 13600,
 12464,
 7800,
 12168,
 7943,
 11050,
 10395,
 11885,
 8402,
 1491,
 8800,
 7861,
 7227,
 11694,
 12244,
 8248,
 10800,
 7064,
 2117,
 10400,
 10000,
 12342,
 9600,
 11606,
 9020,
 9000,
 4590,
 11900,
 9250,
 6979,
 10896,
 6120,
 6000,
 8777,
 3982,
 12677,
 7050,
 13860,
 10793,
 9187,
 10530,
 7200,
 10452,
 7700,
 1936,
 8125,
 9084,
 8750,
 10320,
 10437,
 1680,
 10007,
 7200,
 17503,
 9937,
 12384,
 46589,
 13560,
 10012,
 20896,
 11194,
 18450,
 8125,
 14175,
 11600,
 8633,
 6629,
 11250,
 14442,
 9200,
 2289,
 9600,
 9022,
 11844,
 9945,
 8012,
 4500,
 2887,
 11248,
 16770,
 5062,
 10207,
 5105,
 8089,
 7577,
 4426,
 21535,
 26178,
 5400,
 6120,
 13811,
 6000,
 6420,
 8450,
 4282,
 14331,
 9600,
 12438,
 7630,
 8400,
 5600,
 115149,
 6240,
 9018,
 7162,
 4130,
 8712,
 4671,
 9873,
 13517,
 10140,
 10800,
 10000,
 10542,
 9920,
 6563,
 4426,
 8120,
 8172,
 13286,
 6960,
 21695,
 7314,
 11475,
 6240,
 5389,
 9590,
 11404,
 10000,
 8978,
 10800,
 8544,
 10463,
 10800,
 9313,
 9600,
 6768,
 8450,
 12886,
 5395,
 8963,
 8795,
 11700,
 10593,
 8405,
 8800,
 7750,
 9236,
 10240,
 7930,
 3230,
 10769,
 11616,
 2280,
 12257,
 9100,
 6911,
 8640,
 9430,
 9549,
 14587,
 10421,
 12508,
 9100,
 53504,
 7252,
 8877,
 7819,
 10150,
 14226,
 4500,
 11210,
 13350,
 8400,
 10530,
 7875,
 7153,
 16285,
 9101,
 6300,
 9790,
 10800,
 10142,
 6000,
 12205,
 3182,
 11333,
 9920,
 9158,
 10832,
 8400,
 8197,
 7677,
 13518,
 7200,
 12798,
 4800,
 8199,
 13891,
 9000,
 12274,
 9750,
 21384,
 13400,
 8100,
 10140,
 4438,
 8712,
 9750,
 8248,
 12137,
 11425,
 13265,
 8816,
 6371,
 7226,
 6000,
 12394,
 9900,
 11216,
 14803,
 6130,
 8529,
 28698,
 2544,
 11900,
 3180,
 9548,
 10004,
 7875,
 9600,
 8100,
 1680,
 9525,
 11767,
 12155,
 10440,
 9020,
 8000,
 12665,
 16647,
 9317,
 15523,
 45600,
 9600,
 4435,
 3196,
 7128,
 12095,
 17920,
 6897,
 10970,
 8125,
 10400,
 11029,
 7642,
 11625,
 9672,
 7931,
 8640,
 8750,
 10656,
 6970,
 14762,
 9938,
 6600,
 8750,
 8892,
 12144,
 5720,
 9000,
 25286,
 8834,
 11782,
 7000,
 7024,
 13758,
 9636,
 6204,
 7150,
 5119,
 8393,
 16466,
 15865,
 12160,
 8064,
 11184,
 8414,
 13284,
 7018,
 7056,
 8765,
 7018,
 12919,
 6993,
 7340,
 8712,
 7875,
 14859,
 6173,
 9920,
 13501,
 11500,
 8885,
 12589,
 11600,
 9286,
 6120,
 6270,
 3000,
 2001,
 9000,
 17140,
 13125,
 11029,
 8462,
 8777,
 10237,
 8012,
 10240,
 15611,
 11999,
 9900,
 11838,
 13006,
 8925,
 9100,
 11670,
 8487,
 27650,
 5825,
 10083,
 9675,
 8760,
 24090,
 12640,
 8755,
 7711,
 25000,
 14375,
 8820,
 8163,
 14536,
 14006,
 9360,
 7200,
 7800,
 7200,
 11075,
 9400,
 7136,
 1300,
 7420,
 8450,
 2572,
 7207,
 12227,
 2308,
 11923,
 11316,
 10237,
 9600,
 7390,
 5925,
 10382,
 10800,
 2268,
 7892,
 11639,
 11414,
 2651,
 5900,
 4274,
 9450,
 8816,
 12122,
 12203,
 3182,
 11250,
 10125,
 10880,
 5310,
 10159,
 12046,
 8125,
 9452,
 17671,
 9760,
 8846,
 12456,
 4712,
 10659,
 11717,
 9786,
 6762,
 ...]

In [48]:
lb=min(la)
ub=max(la)

In [49]:
lb

1300

In [50]:
ub

215245

In [46]:
q3

11601.5

In [52]:
print('Ubound',max(la))

Ubound 215245

In [54]:
column_name = 'LotFrontage'

# Calculate the upper bound based on a percentile (e.g., 95th percentile)
upper_percentile = 95
upper_bound = df[column_name].quantile(upper_percentile / 100)

# Replace values above the upper bound with the upper bound
df[column_name] = df[column_name].apply(lambda x: upper_bound if x > upper_bound else x)

# Print the modified DataFrame
print("DataFrame after capping upper-side outliers:")
print(df)

DataFrame after capping upper-side outliers:
        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
...          ...       ...  ...      ...    ...    ...         ...     ...
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
0         2   2008        WD         Normal     208500
1         5   2007        WD         Normal     181500
2         9   2008        WD         Normal     223500
3         2   2006        WD        Abnorml     140000
4        12   2008        WD         Normal     250000
...     ...    ...       ...            ...        ...
1455      8   2007        WD         Normal     175000
1456      2   2010        WD         Normal     210000
1457      5   2010        WD         Normal     266500
1458      4   2010        WD         Normal     142125
1459      6   2008        WD         Normal     147500

[1460 rows x 81 columns]

In [56]:
ub=df["LotFrontage"].describe()["75%"]+1.5*(df["LotFrontage"].describe()["75%"]-df["LotFrontage"].describe()["25%"])
df["LotFrontage"]=np.where(df["LotFrontage"]>ub,ub,df["LotFrontage"])

In [59]:
lower_percentile = 5
lower_bound = df['LotFrontage'].quantile(lower_percentile / 100)
df['LotFrontage'] = df['LotFrontage'].apply(lambda x: lower_bound if x < lower_bound else x)
print("DataFrame after flooring lower-side outliers:")
print(df)

DataFrame after flooring lower-side outliers:
        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
...          ...       ...  ...      ...    ...    ...         ...     ...
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
0         2   2008        WD         Normal     208500
1         5   2007        WD         Normal     181500
2         9   2008        WD         Normal     223500
3         2   2006        WD        Abnorml     140000
4        12   2008        WD         Normal     250000
...     ...    ...       ...            ...        ...
1455      8   2007        WD         Normal     175000
1456      2   2010        WD         Normal     210000
1457      5   2010        WD         Normal     266500
1458      4   2010        WD         Normal     142125
1459      6   2008        WD         Normal     147500

[1460 rows x 81 columns]

In [60]:
print(lower_bound)

34.0